import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles(() => ({
    currentBalance: {
        fontSize: '28px',
        fontWeight: 'bold',
        lineHeight: 0.82,
        color: '#2a323e',
        margin: '20px 0px 10px 0px',
    },
    currentBalanceDollar: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    DepositWrapper: {},
    BalanceWrapper: {
        width: '528px',
        height: '80px',
        margin: '8px 0 0',
        padding: '13px 16px 13px 16px',
        borderRadius: '6px',
        border: 'solid 1px #e1e5ec',
        backgroundColor: '#f7f8fb',
    },
    MaxButtonWrapper: {
        justifyContent: 'right',
    },
    MaxButtonImage: {
        cursor: 'pointer',
    },
    Balance: {
        fontSize: '28px',
        height: '24px',
        fontWeight: 500,
        lineHeight: 0.86,
        color: '#a1acbe',
    },
    BalanceInput: {
        backgroundColor: 'transparent',
        fontSize: '28px',
        fontWeight: 500,
        lineHeight: '0.86',
        color: '#a1acbe',
        outline: 'none',
        '&:focus': {
            border: 'none !important',
            outline: 'none',
        },
    },
    MaxButtonText: {
        fontSize: '24px',
        fontWeight: 500,
        lineHeight: 1,
        textAlign: 'right',
        color: '#2a323e',
        margin: '0px 0.7px 0px 15.3px',
    },
    BalanceInputDollar: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
        marginTop: '10px',
    },
    WalletBalance: {
        marginRight: '0.7px',
        textAlign: 'right',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    AmountOfDays: {
        marginTop: '16px',
        fontSize: '24px',
        fontWeight: 500,
        lineHeight: 1,
        textAlign: 'left',
        color: '#2a323e',
    },
    CTAWrapper: {
        padding: '16px',
        borderRadius: '6px',
        fontSize: '18px',
        fontWeight: 600,
        lineHeight: 1.28,
    },
    CheckboxWrapper: {
        border: '1px solid #5b6c84',
        width: '16px',
        height: '16px',
        padding: '2px',
        marginLeft: '11px',
        marginRight: '11px',
    },
    Checkbox: {
        backgroundColor: '#5b6c84',
        margin: 'auto',
        width: '10px',
        height: '10px',
    },
    Agreement: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
}));
