import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles(() => ({
    Name: {
        width: '73px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
        marginBottom: '4px',
    },
    PublicKey: {
        width: '72px',
        height: '18px',
        fontSize: '12px',
        fontWeight: 500,
        lineHeight: 1.5,
        color: '#a1acbe',
    },
    PublicKeyBold: {
        width: '87px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    copyImage: {
        backgroundImage: 'url(/images/copy-white.svg)',
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '18px',
        height: '18px',
    },
    Status: {
        width: '45px',
        height: '20px',
        padding: '2px 5px 3px 4px',
        fontSize: '12px',
        fontWeight: 600,
    },
    StatusText: {
        textTransform: 'capitalize',
    },
    Active: {
        backgroundColor: 'rgba(6, 182, 79, 0.12)',
        color: '#06b64f',
    },
    Inactive: {
        width: '52px',
        color: '#ec1c26',
        backgroundColor: 'rgba(236, 28, 38, 0.12)',
    },
    Balance: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
        width: '54px',
        height: '20px',
    },
    DollarBalance: {
        width: '36px',
        height: '18px',
        fontSize: '12px',
        fontWeight: 500,
        lineHeight: 1.5,
        color: '#a1acbe',
    },
    ValidatorApr: {
        width: '15px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    ExplorerImage: {
        backgroundImage: 'url(/images/explorer-icon-white.svg)',
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '21.9px',
        height: '21.9px',
        marginRight: '11.1px',
        cursor: 'pointer',
    },
    ChartImage: {
        backgroundImage: 'url(/images/chart-icon-white.svg)',
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '20px',
        height: '20px',
        marginRight: '12px',
        cursor: 'pointer',
    },
    SettingsImage: {
        backgroundImage: 'url(/images/setting-icon-white.svg)',
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '20px',
        height: '20px',
        cursor: 'pointer',
    },
}));
