import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
    Name: {
        '&:nth-of-type(1)': {
            fontSize: 16,
            fontWeight: 500,
            lineHeight: 1.62,
            color: theme.colors.black,
            marginBottom: theme.spacing(1),
        },
        '&:nth-of-type(2)': {
            fontSize: 14,
            fontWeight: 500,
            lineHeight: 1.62,
            color: theme.colors.gray40,
            marginBottom: theme.spacing(0),
        },
    },
    PublicKeyBold: {
        width: '87px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    copyImage: {
        width: 24,
        cursor: 'pointer',
        marginLeft: '6px',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat',
        backgroundImage: `url(/images/copy/${theme.darkMode ? 'white' : 'gray'}.svg)`,
    },
    Status: {
        '& p': {
            fontSize: 14,
            margin: 'auto',
            fontWeight: 500,
            textTransform: 'capitalize',
            // padding: '1px 6px',
        },
    },
    Active: {
        color: theme.colors.primarySuccessDark,
        backgroundColor: theme.colors.primarySuccessRegularOpacity,
    },
    NoValidators: {
        width: 99,
        height: 26,
        color: theme.colors.gray80,
        backgroundColor: theme.colors.gray20,
    },
    Inactive: {
        width: 65,
        color: theme.colors.primaryError,
        backgroundColor: theme.colors.primaryErrorRegular,
    },
    Balance: {
        width: '54px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: theme.colors.black,
    },
    DollarBalance: {
        width: 36,
        height: 18,
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.gray40,
    },
    ValidatorApr: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.black,
    },
    BeaconImage: {
        width: '21.9px',
        height: '21.9px',
        cursor: 'pointer',
        marginRight: '11.1px',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat',
        // backgroundPosition: 'center',
        backgroundImage: `url(/images/beacon/${theme.darkMode ? 'dark' : 'light'}.svg)`,
    },
    ExplorerImage: {
        width: '24px',
        height: '24px',
        cursor: 'pointer',
        marginRight: '12px',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat',
        // backgroundPosition: 'center',
        backgroundImage: `url(/images/chart/${theme.darkMode ? 'dark' : 'light'}.svg)`,
    },
    SettingsImage: {
        width: '24px',
        height: '24px',
        cursor: 'pointer',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat',
        // backgroundPosition: 'center',
        backgroundImage: `url(/images/setting/${theme.darkMode ? 'dark' : 'light'}.svg)`,
    },
}));
