import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
    Name: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.black,
        marginBottom: theme.spacing(1),
        '&:nth-of-type(2)': {
            color: theme.colors.gray40,
            marginBottom: theme.spacing(0),
        },
    },
    PublicKeyBold: {
        width: '87px',
        height: '20px',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: '#5b6c84',
    },
    copyImage: {
        width: 24,
        marginLeft: '6px',
        backgroundSize: 'contain',
        backgroundRepeat: 'no-repeat',
        backgroundImage: `url(/images/copy-${theme.darkMode ? 'white' : 'gray'}.svg)`,
    },
    Status: {
        width: '45px',
        height: '20px',
        padding: '2px 5px 3px 4px',
        fontSize: '12px',
        fontWeight: 600,
    },
    StatusText: {
        textTransform: 'capitalize',
    },
    Active: {
        backgroundColor: theme.colors.primarySuccessRegular,
        color: theme.colors.primarySuccessDark,
    },
    Inactive: {
        width: '52px',
        color: '#ec1c26',
        backgroundColor: theme.colors.primaryErrorRegular,
    },
    Balance: {
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: 1.43,
        color: theme.colors.black,
        width: '54px',
        height: '20px',
    },
    DollarBalance: {
        width: 36,
        height: 18,
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.gray40,
    },
    ValidatorApr: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.black,
    },
    BeaconImage: {
        backgroundImage: `url(/images/explorer/${theme.darkMode ? 'white' : 'gray'}.svg)`,
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '21.9px',
        height: '21.9px',
        marginRight: '11.1px',
        cursor: 'pointer',
    },
    ExplorerImage: {
        backgroundImage: `url(/images/chart/${theme.darkMode ? 'white' : 'gray'}.svg)`,
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '24px',
        height: '24px',
        marginRight: '12px',
        cursor: 'pointer',
    },
    SettingsImage: {
        backgroundImage: `url(/images/setting/${theme.darkMode ? 'dark' : 'light'}.svg)`,
        // backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'contain',
        width: '24px',
        height: '24px',
        cursor: 'pointer',
    },
}));
