// ------------------------------------------------
// This file is auto-generated by scripts/createRead.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract, useBlockNumber } from "wagmi";

import {
  getSSVNetworkDetails,
  useSSVNetworkDetails,
} from "@/hooks/use-ssv-network-details";
import { GetterABI } from "@/lib/abi/getter.ts";

import { readContractQueryOptions } from "wagmi/query";
import { getChainId } from "@wagmi/core";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

export const getPendingOwnerQueryOptions = () =>
  readContractQueryOptions(config, {
    abi: GetterABI,
    chainId: getChainId(config),
    address: getSSVNetworkDetails().getterContractAddress,
    functionName: "pendingOwner",
  });

type QueryOptions = UseReadContractParameters<
  typeof GetterABI,
  "pendingOwner"
>["query"];

export const fetchPendingOwner = () =>
  queryClient.fetchQuery(getPendingOwnerQueryOptions());

export const usePendingOwner = (
  options: QueryOptions & { watch?: boolean } = { enabled: true },
) => {
  const { getterContractAddress } = useSSVNetworkDetails();

  const blockNumber = useBlockNumber({ watch: options.watch });

  return useReadContract({
    abi: GetterABI,
    address: getterContractAddress,
    functionName: "pendingOwner",

    blockNumber: options.watch ? blockNumber.data : undefined,
    query: { ...options },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createRead.js
// ------------------------------------------------
