overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@metamask/sdk-communication-layer@>=0.16.0 <=0.33.0': '>=0.33.1'
  '@metamask/sdk@>=0.16.0 <=0.33.0': '>=0.33.1'
  '@octokit/endpoint@>=10.0.0 <10.1.3': '>=10.1.3'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  '@octokit/request-error@>=6.0.0 <6.1.7': '>=6.1.7'
  '@octokit/request@>=9.0.0-beta.1 <9.2.1': '>=9.2.1'
  '@sentry/browser@>=8.0.0-alpha.1 <8.33.0': '>=8.33.0'
  base-x@<=3.0.10: '>=3.0.11'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cipher-base@<=1.0.4: '>=1.0.5'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  elliptic@<6.6.0: '>=6.6.0'
  elliptic@<=6.6.0: '>=6.6.1'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.5 <4.4.1: '>=4.4.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  image-size@>=1.1.0 <1.2.1: '>=1.2.1'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  micromatch@<4.0.8: '>=4.0.8'
  min-document@<=2.19.0: '>=2.19.1'
  node-forge@<1.3.2: '>=1.3.2'
  on-headers@<1.1.0: '>=1.1.0'
  pbkdf2@<=3.1.2: '>=3.1.3'
  pbkdf2@>=3.0.10 <=3.1.2: '>=3.1.3'
  secp256k1@=5.0.0: '>=5.0.1'
  secp256k1@>=4.0.0 <4.0.4: '>=4.0.4'
  send@<0.19.0: '>=0.19.0'
  serve-static@<1.16.0: '>=1.16.0'
  sha.js@<=2.4.11: '>=2.4.12'
  tmp@<=0.2.3: '>=0.2.4'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
