import { Theme } from '@mui/material/styles';
import { makeStyles } from '@mui/styles';

const imageDefaultProperties = {
  width: 24,
  height: 24,
  cursor: 'pointer',
  backgroundSize: 'contain',
  backgroundPosition: 'center',
  backgroundRepeat: 'no-repeat',
};

const text = {
  fontSize: 24,
  lineHeight: 1.24,
  letterSpacing: -0.25,
};

export const useStyles = makeStyles((theme: Theme) => ({
  WhiteWrapper: {
    backgroundColor: theme.colors.gray0,
  },
  SecondaryHeaderWrapper: {
    gap: 16,
    alignItems: 'center',
  },
  Line: {
    width: 1,
    height: 24,
    flexGrow: 0,
    backgroundColor: '#cbd3e5',
    transform: 'rotate(-180deg)',
  },
  HeaderWrapper: {},
  Wrapper: {
    paddingTop: 24,
    margin: 'auto',
    maxWidth: 1320,
    gap: (props: any) => props.mainFlow ? 28 : 0,
    paddingBottom: (props: any) => props.mainFlow ? 34 : 24,
    '@media only screen and (max-width: 1400px)': {
      margin: 'auto',
      maxWidth: '80%',
    },
  },
  BackButtonWrapper: {
    marginBottom: 20,
  },
  CancelWrapper: {
    justifyContent: 'flex-end',
    gap: 8,
    '& p': {
      fontSize: 16,
      fontWeight: 600,
      lineHeight: 1.25,
      cursor: 'pointer',
      color: theme.colors.gray40,
    },
  },
  CancelImage: {
    width: 20,
    height: 20,
    cursor: 'pointer',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundImage: `url(/images/x/${theme.darkMode ? 'dark' : 'light'}.svg)`,
  },
  ChildWrapper: {},
  DialogWrapper: {
    width: 424,
    padding: 32,
    height: 222,
    borderRadius: 16,
    backgroundColor: theme.colors.white,
  },
  ButtonsWrapper: {
    gap: 24,
  },
  HeaderText: {
    ...text,
    fontWeight: 800,
    color: theme.colors.gray90,
  },
  subHeaderText: {
    ...text,
    color: theme.colors.gray80,
  },
  BackNavigation: {
    width: 14,
    height: 14,
    cursor: 'pointer',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundImage: 'url(/images/backButton/light.svg)',
  },
  Settings: {
    right: 0,
    width: 272,
    display: 'flex',
    borderRadius: 8,
    position: 'absolute',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: theme.colors.white,
    boxShadow: '0 12px 40px 0 #0116271e',
    border: `solid 1px ${theme.colors.gray10}`,
  },
  Button: {
    gap: 12,
    height: 54,
    padding: 16,
    flexGrow: 0,
    fontSize: 16,
    display: 'flex',
    fontWeight: 600,
    lineHeight: 1.25,
    cursor: 'pointer',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderBottom: `solid 1px ${theme.colors.gray20}`,
    '&:hover': {
      backgroundColor: theme.colors.gray10,
    },
    '& p': {
      color: theme.colors.gray90,
    },
    '&:last-child': {
      '& p': {
        color: theme.colors.primaryError,
      },
      borderBottom: 'none',
    },
  },
  SettingsImage: {
    backgroundImage: 'url(/images/operator_settings/settings.svg)',
    ...imageDefaultProperties,
  },
  MetadataImage: {
    backgroundImage: 'url(/images/operator_settings/metadata.svg)',
    ...imageDefaultProperties,
  },
  RemoveImage: {
    backgroundImage: 'url(/images/operator_settings/metadata.svg)',
    ...imageDefaultProperties,
  },
  CompleteProfile: {
    gap: 4,
    height: 34,
    fontSize: 16,
    marginLeft: 23,
    display: 'flex',
    borderRadius: 8,
    fontWeight: 500,
    lineHeight: 1.62,
    padding: '4px 8px',
    alignItems: 'center',
    color: theme.colors.gray90,
    backgroundColor: 'rgba(253, 218, 72, 0.2)',
  },
  Options: {
    width: 40,
    height: 40,
    float: 'right',
    cursor: 'pointer',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundImage: `url(/images/kebab/${theme.darkMode ? 'dark' : 'light'}.svg)`,
  },
  SettingsWrapper: {
    position: 'relative',
  },
  FirstSquare: {
    marginBottom: theme.spacing(6),
  },
  currentBalance: {
    fontSize: 28,
    fontWeight: 800,
    lineHeight: 1.24,
    letterSpacing: -0.5,
    color: theme.colors.black,
    marginBottom: theme.spacing(1),
  },
  currentBalanceDollar: {
    fontSize: 16,
    fontWeight: 500,
    lineHeight: 1.62,
    color: theme.colors.gray40,
  },
  BalanceWrapper: {
    height: 93,
    borderRadius: 8,
    margin: '8px 0 0',
    padding: theme.spacing(4, 5, 4, 5),
    backgroundColor: theme.colors.gray0,
    border: `solid 1px ${theme.colors.gray20}`,
  },
  MaxButtonWrapper: {
    justifyContent: 'right',
  },
  MaxButton: {
    width: 80,
    height: 36,
    fontSize: 16,
    borderRadius: 8,
    fontWeight: 600,
    lineHeight: 1.25,
    cursor: 'pointer',
    padding: '8px 22px 8px 23px',
    color: theme.colors.primaryBlue,
    backgroundColor: theme.colors.tint90,
  },
  Balance: {
    fontSize: 28,
    fontWeight: 500,
    lineHeight: 0.86,
    border: 'none !important',
    color: theme.colors.black,
    backgroundColor: theme.colors.gray0,
    '&:focus': {
      '-webkit-appearance': 'none',
      outline: 'none',
    },
    '&::-webkit-outer-spin-button, &::-webkit-inner-spin-button': {
      '-webkit-appearance': 'none',
      display: 'none',
    },
  },
  BalanceInput: {
    backgroundColor: 'transparent',
    fontSize: '28px',
    fontWeight: 500,
    lineHeight: '0.86',
    color: '#a1acbe',
    outline: 'none',
    '&:focus': {
      border: 'none !important',
      outline: 'none',
    },
  },
  MaxButtonText: {
    width: 52,
    height: 35,
    fontSize: 28,
    fontWeight: 500,
    lineHeight: 1.24,
    letterSpacing: -0.5,
    margin: theme.spacing(0, 0, 1, 5),
    color: theme.colors.black,
  },
  BalanceInputDollar: {
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: 1.43,
    color: '#5b6c84',
    marginTop: '10px',
  },
  CheckboxWrapper: {
    width: '16px',
    height: '16px',
    padding: '2px',
    marginLeft: '11px',
    marginRight: '11px',
    border: '1px solid #5b6c84',
  },
  Checkbox: {
    backgroundColor: '#5b6c84',
    margin: 'auto',
    width: '10px',
    height: '10px',
  },
  Agreement: {
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: 1.43,
    color: '#5b6c84',
  },
}));