import { makeStyles } from '@material-ui/core';
import { createStyles, Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) => createStyles({
    selectButton: {
        height: 73,
        width: '100%',
        borderRadius: 8,
        fontWeight: 500,
        fontSize: '14px',
        color: '#2A323E',
        maxWidth: '100%',
        textAlign: 'left',
        cursor: 'pointer',
        margin: theme.spacing(0),
        marginTop: theme.spacing(1),
        backgroundColor: theme.colors.white,
        border: `solid 1px ${theme.colors.gray30}`,
        padding: theme.spacing(3, 5),
    },
    SelectOperatorHeader: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.black,
    },
    buttonArrow: {
        height: '20%',
        float: 'right',
        marginRight: '10px',
        marginTop: '5px',
        transitionDuration: '0.3s',
        transform: 'rotate(180deg)',
    },
    DropDownMenuHeader: {
        height: 36,
        lineHeight: 1.5,
        fontSize: '12px',
        fontWeight: 'bold',
        position: 'sticky',
        color: theme.colors.gray40,
        backgroundColor: theme.colors.white,
        border: `solid 1px ${theme.colors.gray20}`,
        padding: theme.spacing(2, 5),
    },
    YearlyFeeHeader: {
        paddingLeft: '7.5%',
    },
    arrowSelected: {
        transform: 'rotate(0deg)',
        transitionDuration: '0.3s',
    },
    selected: {
        borderRadius: '6px 6px 0px 0px',
        borderBottom: 'none',
    },
    menuLoader: {
        width: '500px',
        height: '10px',
        transition: 'width 3s',
        // transition: 'width 6s ease-in-out',
        backgroundColor: 'blue',
        // textAlign: 'center',
    },
    menuWrapper: {
        // width: '100%',
        // '@media (max-width: 1025)': {
        //     width: '75%',
        // },
        // '@media (max-width: 768px)': {
        //     width: '50%',
        // },
        // '@media (max-width: 480px)': {
        //     width: '90%',
        // },
        position: 'relative',
        border: '1px solid #5B6C84',
        borderTop: 'none',
        background: '#FFFFFF',
        borderRadius: '0px 0px 6px 6px',
        height: '362px',
        overflow: 'scroll',
        zIndex: theme.opacity.highPriority,
    },
    menuItem: {
        height: 73,
        cursor: 'pointer',
        backgroundColor: theme.colors.white,
        padding: theme.spacing(3, 5),
        '&:hover': {
            // backgroundColor: 'rgba(220, 224, 232, 0.25)',
        },
    },
    NameAndAddressWrapper: {
        maxWidth: 109,
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
    },
    Address: {
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.gray40,
    },
    disable: {
        backgroundColor: theme.colors.gray20,
    },
    formControl: {
        margin: theme.spacing(0),
        marginTop: theme.spacing(1),
        width: '100%',
        maxWidth: '100%',
    },
    select: {
        '& .MuiSelect-outlined': {
            paddingTop: 5,
            paddingBottom: 5,
            minHeight: 35,
        },
    },
    selectPaper: {
        shadow: '0px',
        border: '2px solid #3f51b5',
        boxShadow: 'none',
        borderRadius: '0',
        borderTop: 'none',
        marginTop: '43px',
        '& ul': {
            padding: 3,
            '@media (max-width: 480px)': {
                maxHeight: '200px',
                minWidth: '327px',
            },
            maxHeight: 362,
        },
        '& li': {
            width: 'inherit',
        },
    },
    verifiedWrapper: {},
    Fee: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.black,
    },
    FeeDollar: {
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.gray40,
    },
    verifiedText: {
        gap: 8,
        width: 91,
        height: 26,
        borderRadius: 4,
        padding: '1px 8px',
        alignItems: 'center',
        justifyContent: 'center',
        color: theme.colors.primarySuccessDark,
        backgroundColor: theme.colors.primarySuccessRegularOpacity,
    },
    VerifiedIcon: {
        width: 16,
        height: 16,
        margin: 'auto',
        display: 'block',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundImage: 'url(/images/checkmark/verified.svg)',
    },
    DappNode: {
        gap: 8,
        width: 110,
        height: 26,
        fontSize: 14,
        borderRadius: 4,
        fontWeight: 500,
        lineHeight: 1.62,
        textAlign: 'left',
        color: ' #8090ea',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: ' #dfe5ff',
    },
    DappNodeIcon: {
        width: 16,
        height: 16,
        margin: 'auto',
        display: 'block',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundImage: 'url(/images/checkmark/verified.svg)',
    },
    chartIcon: {
        width: 24,
        height: 24,
        float: 'right',
        alignContent: 'flex-end',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundImage: 'url(/images/chart/gray.svg)',
    },
}));
