// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";

import { TokenABI } from "@/lib/abi/token";

import { readContractQueryOptions } from "wagmi/query";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

export const getOwnerQueryOptions = (tokenAddress: `0x${string}`) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address: tokenAddress,
    functionName: "owner",
  });

type QueryOptions = UseReadContractParameters<
  typeof TokenABI,
  "owner"
>["query"];

export const fetchOwner = (tokenAddress: `0x${string}`) =>
  queryClient.fetchQuery(getOwnerQueryOptions(tokenAddress));

export const useOwner = (
  tokenAddress: `0x${string}`,

  options: QueryOptions = { enabled: true },
) => {
  return useReadContract({
    abi: TokenABI,
    address: tokenAddress,
    functionName: "owner",

    query: { ...options },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
