// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";

import { TokenABI } from "@/lib/abi/token";

import { readContractQueryOptions } from "wagmi/query";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

export const getNameQueryOptions = (tokenAddress: `0x${string}`) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address: tokenAddress,
    functionName: "name",
  });

type QueryOptions = UseReadContractParameters<typeof TokenABI, "name">["query"];

export const fetchName = (tokenAddress: `0x${string}`) =>
  queryClient.fetchQuery(getNameQueryOptions(tokenAddress));

export const useName = (
  { tokenAddress }: { tokenAddress?: `0x${string}` },
  options: QueryOptions = { enabled: true },
) => {
  return useReadContract({
    abi: TokenABI,
    address: tokenAddress,
    functionName: "name",

    query: { ...options, enabled: tokenAddress && options?.enabled },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
