(async () => {
  /* eslint-disable @typescript-eslint/no-var-requires */
  /* eslint-disable no-undef */
  const fs = require("fs");
  const path = require("path");
  const prettier = require("prettier");
  const typescriptParser = require("prettier/parser-typescript");
  const babelParser = require("prettier/parser-babel");
  const { isEqual, kebabCase } = await import("lodash-es");

  const mainnetAbi = require("../src/lib/abi/mainnet/v4/getter.json");

  const holeskyAbi = require("../src/lib/abi/holesky/v4/getter.json").filter(
    (item) => {
      const mainnetItem = mainnetAbi.find((f) => f?.name === item?.name);
      return !isEqual(mainnetItem, item);
    }
  );

  const folder = path.join(
    path.dirname(__dirname),
    "src/lib/contract-interactions/read"
  );

  if (!fs.existsSync(folder)) {
    console.log("Creating folder: ", folder);
    fs.mkdirSync(folder, { recursive: true });
  }

  fs.readdirSync(folder).forEach((file) => {
    fs.unlinkSync(path.join(folder, file));
  });

  const readFns = holeskyAbi.filter(
    (item) =>
      item.type === "function" &&
      (item.stateMutability == "view" || item.stateMutability == "pure")
  );

  const readFnsMainnet = mainnetAbi.filter(
    (item) =>
      item.type === "function" &&
      (item.stateMutability == "view" || item.stateMutability == "pure")
  );

  const createWriteFn = (isTestnet, item) => {
    const functionName = item.name;
    const hookName = `use${capitalizeFirstLetter(functionName)}${isTestnet ? "_Testnet" : ""}`;
    const fileName = `${kebabCase(hookName)}.ts`;
    const filePath = path.join(folder, `${fileName}`);
    const hasInputs = Boolean(item.inputs?.length);

    const networkName = isTestnet ? "holesky" : "mainnet";

    const abiName = isTestnet ? "HoleskyV4GetterABI" : "MainnetV4GetterABI";

    const content = `
// ------------------------------------------------
// This file is auto-generated by createWriteContractQueries.js
// ------------------------------------------------

import { useReadContract } from "wagmi";
import { useSSVNetworkDetails } from '@/hooks/use-ssv-network-details';
import { ${abiName} } from "@/lib/abi/${networkName}/v4/getter";${
      hasInputs
        ? `
import type {  ExtractAbiFunction } from "abitype";
import  { AbiInputsToParams, paramsToArray, extractAbiFunction } from "@/lib/contract-interactions/utils";`
        : ""
    }

${hasInputs ? `type Fn = ExtractAbiFunction<typeof ${abiName}, "${functionName}">;` : ""}
${hasInputs ? `const abiFunction = extractAbiFunction(${abiName},"${functionName}");` : ""}

export const ${hookName} = (${hasInputs ? 'params: AbiInputsToParams<Fn["inputs"]>' : ""}) => {
  const { getterContractAddress } = useSSVNetworkDetails()

  return useReadContract({
      abi: ${abiName},
      address: getterContractAddress,
      functionName: "${functionName}",
      ${hasInputs ? "args: paramsToArray({ params, abiFunction })," : ""}
       ${
         hasInputs
           ? `query: {
        enabled: Boolean(params),
      },`
           : ""
       }
    });
};
`;
    fs.mkdirSync(folder, { recursive: true });
    prettier
      .format(content.trim(), {
        parser: "typescript",
        plugins: [typescriptParser, babelParser],
      })
      .then((prettifiedCode) => {
        fs.writeFileSync(filePath, prettifiedCode);
        // fs.chmodSync(filePath, 0o444);
        console.log(`File created: ${filePath}`);
      });
  };
  readFnsMainnet.forEach(createWriteFn.bind(null, false));
  readFns.forEach(createWriteFn.bind(null, true));

  function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
})();
