(async () => {
  /* eslint-disable @typescript-eslint/no-var-requires */
  /* eslint-disable no-undef */
  const fs = require("fs");
  const path = require("path");
  const prettier = require("prettier");
  const typescriptParser = require("prettier/parser-typescript");
  const babelParser = require("prettier/parser-babel");

  const folder = path.join(
    path.dirname(__dirname),
    "src/lib/contract-interactions/erc-20/read",
  );

  if (!fs.existsSync(folder)) {
    console.log("Creating folder: ", folder);
    fs.mkdirSync(folder, { recursive: true });
  }

  fs.readdirSync(folder).forEach((file) => {
    fs.unlinkSync(path.join(folder, file));
  });

  const tokenAbi = require("../src/lib/abi/token.json");

  const readFns = tokenAbi.filter(
    (item) =>
      item.type === "function" &&
      (item.stateMutability === "view" || item.stateMutability === "pure"),
  );

  const createReadHook = (item) => {
    const functionName = item.name;
    const hookName = `use${capitalizeFirstLetter(functionName)}`;
    const fileName = `${kebabCase(hookName)}.ts`;
    const filePath = path.join(folder, `${fileName}`);
    const hasInputs = Boolean(item.inputs?.length);

    const content = `
// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";
${hasInputs ? `import { isUndefined } from "lodash-es";` : ""}
import { TokenABI } from "@/lib/abi/token";${
      hasInputs
        ? `
import type {
  AbiInputsToParams} from "@/lib/contract-interactions/utils";
import {
  paramsToArray,
  extractAbiFunction,
} from "@/lib/contract-interactions/utils";`
        : ""
    }
${hasInputs ? 'import type { ExtractAbiFunction } from "abitype";' : ""}
import { readContractQueryOptions } from "wagmi/query";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

${hasInputs ? `type Fn = ExtractAbiFunction<typeof TokenABI, "${functionName}">;` : ""}
${hasInputs ? `const abiFunction = extractAbiFunction(TokenABI,"${functionName}");` : ""}

export const get${capitalizeFirstLetter(functionName)}QueryOptions = (tokenAddress: \`0x\${string}\`${hasInputs ? ', params: AbiInputsToParams<Fn["inputs"]>' : ""}) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address: tokenAddress,
    functionName: "${functionName}",
    ${hasInputs ? "args: paramsToArray({ params, abiFunction })," : ""}
  });

type QueryOptions = UseReadContractParameters<
  typeof TokenABI,
  "${functionName}"
>["query"];

export const fetch${capitalizeFirstLetter(functionName)} = (tokenAddress: \`0x\${string}\`${hasInputs ? ', params: AbiInputsToParams<Fn["inputs"]>' : ""}) =>
  queryClient.fetchQuery(get${capitalizeFirstLetter(functionName)}QueryOptions(tokenAddress${hasInputs ? ", params" : ""}));

export const ${hookName} = (
  tokenAddress: \`0x\${string}\`,
  ${hasInputs ? 'params: AbiInputsToParams<Fn["inputs"]>,' : ""}
  options: QueryOptions = {enabled: true}
) => {
  ${hasInputs ? "const args = paramsToArray({ params, abiFunction })" : ""}

  return useReadContract({
    abi: TokenABI,
    address: tokenAddress,
    functionName: "${functionName}",
    ${hasInputs ? "args," : ""}
    ${
      hasInputs
        ? `query: {
      ...options,
      enabled: options?.enabled && args.every((arg) => !isUndefined(arg)),
    },`
        : "query: {...options},"
    }
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
`;

    fs.mkdirSync(folder, { recursive: true });
    prettier
      .format(content.trim(), {
        parser: "typescript",
        plugins: [typescriptParser, babelParser],
      })
      .then((prettifiedCode) => {
        fs.writeFileSync(filePath, prettifiedCode);
        console.log(`File created: ${filePath}`);
      });
  };

  readFns.forEach(createReadHook);

  function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }

  function kebabCase(string) {
    return string
      .replace(/([a-z])([A-Z])/g, "$1-$2")
      .replace(/[\s_]+/g, "-")
      .toLowerCase();
  }
})();
