// ------------------------------------------------
// This file is auto-generated by createWriteContractQueries.js
// ------------------------------------------------

import { useWriteContract } from "wagmi";
import { useSSVNetworkDetails } from "@/hooks/use-ssv-network-details";
import type {
  BAppEvent,
  MutationOptions,
} from "@/lib/contract-interactions/utils/useWaitForTransactionReceipt";
import { useWaitForTransactionReceipt } from "@/lib/contract-interactions/utils/useWaitForTransactionReceipt";
import { BAppABI } from "@/lib/abi/b-app/b-app";
import type { WriteContractErrorType } from "@wagmi/core";
import type { WaitForTransactionReceiptErrorType } from "viem";

// type State = "idle" | "confirming" | "mining" | "mined" | "error";

export const useAcceptOwnership = () => {
  const { bAppContractAddress } = useSSVNetworkDetails();

  const wait = useWaitForTransactionReceipt<BAppEvent>([
    "useAcceptOwnership",
    bAppContractAddress,
  ]);
  const mutation = useWriteContract();

  const send = (options: MutationOptions<BAppEvent> = {}) => {
    return mutation.writeContractAsync(
      {
        abi: BAppABI,
        address: bAppContractAddress,
        functionName: "acceptOwnership",
      },
      {
        onSuccess: (hash) => options.onConfirmed?.(hash),
        onError: (error) => options.onError?.(error as WriteContractErrorType),
      },
    );
  };

  const write = (options: MutationOptions<BAppEvent> = {}) => {
    options.onInitiated?.();
    return mutation
      .writeContractAsync(
        {
          abi: BAppABI,
          address: bAppContractAddress,
          functionName: "acceptOwnership",
        },
        {
          onSuccess: (hash) => options.onConfirmed?.(hash),
          onError: (error) =>
            options.onError?.(error as WriteContractErrorType),
        },
      )
      .then((result) =>
        wait.mutateAsync(result, {
          onSuccess: (receipt) => options.onMined?.(receipt),
          onError: (error) =>
            options.onError?.(error as WaitForTransactionReceiptErrorType),
        }),
      );
  };

  const isPending = mutation.isPending || wait.isPending;

  return {
    error: mutation.error || wait.error,
    isSuccess: wait.isSuccess,
    isPending,
    mutation,
    write,
    send,
    wait,
  };
};
