import { makeStyles, Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) => ({
    Wrapper: {
        height: 50,
        borderRadius: 8,
        backgroundColor: theme.colors.white,
        border: `solid 1px ${theme.colors.gray30}`,
        padding: theme.spacing(3, 4, 3, 5),
    },
    PublicKey: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
        color: theme.colors.gray90,
    },
    CopyImage: {
        width: 24,
        height: 24,
        cursor: 'pointer',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        marginRight: theme.spacing(2),
        marginLeft: theme.spacing(10),
        backgroundImage: `url(/images/copy/${theme.darkMode ? 'light' : 'dark'}.svg)`,
    },
    ExplorerImage: {
        width: 24,
        height: 24,
        cursor: 'pointer',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        backgroundImage: `url(/images/explorer/${theme.darkMode ? 'white' : 'gray'}.svg)`,
    },
    inputAddonContainer: {
        borderLeft: '1px solid gainsboro',
        width: 40,
        minHeight: '48px',
        position: 'absolute',
        right: 0,
        top: 0,
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        alignContent: 'center',
        cursor: 'pointer',
    },
    inputAddonImage: {
        width: 23,
        height: 23,
        margin: 'auto',
    },
    wideWidthInput: {
        width: '100%',
        padding: 0,
        height: '48px',
        borderRadius: '6px',
    },
    input: {
        width: 'calc(86% - 3px)',
        fontSize: '14px',
        paddingLeft: '10px',
        [theme.breakpoints.down('lg')]: {
            width: 'calc(86% - 13px)',
        },
    },
}));
