import { Theme } from '@mui/material';
import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme: Theme) => ({
    FiltersWrapper: {
        width: 154,
        height: 50,
        borderRadius: 8,
        cursor: 'pointer',
        position: 'relative',
        alignContent: 'center',
        border: `solid 1px ${theme.colors.gray30}`,
        backgroundColor: theme.colors.white,
    },
    Bold: {
        border: `solid 1px ${theme.colors.primaryBlue}`,
        backgroundColor: theme.colors.tint90,
    },
    FilterImg: {
        width: 24,
        height: 24,
        cursor: 'pointer',
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        marginLeft: theme.spacing(4),
        backgroundRepeat: 'no-repeat',
        backgroundImage: `url(/images/filter/${theme.darkMode ? 'dark' : 'light'}.svg)`,
    },
    FilterText: {
        fontSize: 16,
        fontWeight: 500,
        lineHeight: 1.62,
        color: theme.colors.gray90,
        marginLeft: theme.spacing(5),
    },
    FilterTextBlue: {
        width: 20,
        height: 20,
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.62,
        borderRadius: '50%',
        textAlign: 'center',
        margin: '3px 0 3px 16px',
        color: theme.colors.white,
        padding: '0 6.5px 0 5.9px',
        backgroundColor: theme.colors.primaryBlue,
    },
    Popup: {
        gap: 18,
        top: 50,
        right: 0,
        width: 272,
        height: 152,
        zIndex: 9999,
        borderRadius: 16,
        position: 'absolute',
        padding: theme.spacing(8, 8, 4, 8),
        backgroundColor: theme.colors.white,
        border: `solid 1px ${theme.colors.gray20}`,
        boxShadow: '0 12px 40px 0 rgba(1, 22, 39, 0.12)',
    },
    Item: {
        height: 56,
        marginBottom: 8,
        alignItems: 'center',
    },
    Checkbox: {
        width: 24,
        height: 24,
        marginLeft: 20,
        borderRadius: 8,
        cursor: 'pointer',
        backgroundColor: theme.colors.gray10,
        border: `1px solid ${theme.colors.gray40}`,
    },
    Checked: {
        width: 24,
        height: 24,
        border: 'none',
        backgroundImage: `url(/images/checkbox/${theme.darkMode ? 'dark' : 'light'}.svg)`,
    },
    Text: {
        fontSize: 16,
        fontWeight: 600,
        lineHeight: 1.25,
        textAlign: 'center',
        color: theme.colors.gray90,
    },
}));
