import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';

export const useStyles = makeStyles((theme: Theme) => ({
  ErrorMessage: {
    gap: 10,
    height: 47,
    display: 'flex',
    borderRadius: 2,
    marginTop: '20px',
    padding: '12px 16px',
    alignItems: 'center',
    flexDirection: 'row',
    color: theme.colors.black,
    border: 'solid 1px #ec1c26',
    justifyContent: 'flex-start',
    backgroundColor: theme.colors.primaryErrorRegular,
  },
  EligibleWrapper: {
    marginTop: 20,
  },
  Eligible: {
    height: 93,
    borderRadius: 8,
    border: 'solid 1px #bbe4fd',
    padding: '27px 35px 26px 32px',
    backgroundColor: theme.colors.tint90,
  },
  EligibleAmount: {
    fontSize: 28,
    fontWeight: 500,
    lineHeight: 1.24,
    textAlign: 'left',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '-0.5px',
    color: theme.colors.shade80,
  },
  CompanyIcon: {
    height: 40,
    width: 28.5,
    marginRight: 12,
    marginLeft: 'auto',
    backgroundImage: `url(/images/logo/${theme.darkMode ? 'small_light' : 'small_light'}.svg)`,
  },
  CtaButton: {
    marginTop: 40,
  },
  RewardWrapper: {
    width: 584,
    height: 50,
    borderRadius: 8,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 20px 12px 20px',
    marginTop: 20,
    backgroundColor: theme.colors.gray0,
    border: `1px solid ${theme.colors.gray20}`,
  },
  RecipientWrapper: {
    width: 584,
    height: 50,
    borderRadius: 8,
    display: 'flex',
    // justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 20px 12px 20px',
    marginTop: 8,
    backgroundColor: theme.colors.gray10,
    border: `1px solid ${theme.colors.gray20}`,
  },
  RecipientAddress: {
    fontSize: 15,
    fontWeight: 600,
    color: theme.colors.gray60,
  },
  RewardTitle: {
    fontSize: 16,
    fontWeight: 500,
    color: theme.colors.gray90,
  },
  RewardAmount: {
    fontSize: 16,
    fontWeight: 700,
    color: theme.colors.gray90,
  },
}));
